### ISSUE TITLE
No such file or directory: 'C:\\Windows\\Fonts\\seguiemj.ttf

### ISSUE THREAD

**Issue by gitty-git-git** [UWPX/Emoji-List-Parser#2]
I am running this under Ubuntu with Python3 but I get the following error:

```
$ python3 main.py
Started emoji list download from: https://unicode.org/Public/emoji/13.0/emoji-test.txt
Finished emoji list download.
Started parsing emoji list...
Finished parsing emoji. Found 4174 emoji in 101 subgroups.
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    gen = GenCSharp(r"C:\Windows\Fonts\seguiemj.ttf", url)
  File "/home/Emoji-List-Parser/gen_c_sharp.py", line 11, in __init__
    with open(fontPath, 'rb') as fontfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\Fonts\\seguiemj.ttf'
```

**Comment by COM8** [comment]
Try commenting out the following lines in the `main.py` file:
https://github.com/UWPX/Emoji-List-Parser/blob/4b2c5fcf16c27e5235290a6ea403e79b923fe4f0/main.py#L9-L11

It's trying to load the Windows 10 Segoe UI font file, which is not available under Linux (Ubuntu).
I was using it to generate C# definitions for all Emoji ;)
